### PR TITLE
Solved point 1 in readme

### LINKED ISSUE #3: Actor in his underware, singing into a candlestick, weird scientology ...
What's his name?  Help!

@chaintip

### PR DESCRIPTION
**Pull request by mebeim**
@chaintip fixes #3

### CODE REVIEW

**Comment by chaintip** [comment]
If this pull request is merged to fix issue [#3](http://github.chaintip.org/alwaysAn0n/chain-tip-test/issues/3) first, @mebeim will claim the `0.00080533 BCH`| `~   1.22 USD` [bounty](http://github.chaintip.org/chaintip/bounties/issues/14) and all future tips to the issue.

**Comment by alwaysAn0n** [comment]
YES, THAT'S IT!  Thanks @mebeim !

**Comment by chaintip** [comment]
Nice work @mebeim! Your pull request has been merged and the [bounty](http://github.chaintip.org/chaintip/bounties/issues/14) of `0.00080533 BCH`| `~   1.20 USD` has been sent to your wallet.

**Comment by mebeim** [comment]
Well, this actually [works pretty well](https://blockchair.com/bitcoin-cash/transaction/d7d380e3bc8ff56ed8263a4b8803c07f920d8d1fc1eb2fb4ac98eb9d80849624). I love it, awesome idea! @alwaysAn0n

**Comment by tea-spoon** [comment]
Thanks for trying it out @mebeim @chaintip! Know anyone else who might like it? Please spread the word :)

**Comment by chaintip** [comment]
@mebeim, you've [been sent](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4rtckqxst32mjffa5fgeepfy720v7cmcc50d) `0.00134057 BCH`| `~   2.00 USD` by @tea-spoon via [chaintip](http://www.chaintip.org).

**Pull request merged**
