### PR TITLE
Answers thing number 2

### LINKED ISSUE #2: Purely peer-to-peer version of electronic cash
What's the name of this thing?  Someone help!

@chaintip

### PR DESCRIPTION
**Pull request by mesquka**
@chaintip fixes #2

### CODE REVIEW

**Comment by chaintip** [comment]
If this pull request is merged to fix issue [#2](http://github.chaintip.org/alwaysAn0n/chain-tip-test/issues/2) first, @mesquka will claim the `0.00229159 BCH`| `~   3.48 USD` [bounty](http://github.chaintip.org/chaintip/bounties/issues/13) and all future tips to the issue.

**Comment by alwaysAn0n** [comment]
@mesquka That's very, very close but it's not quite descriptive enough.  I think it might be a two word answer.  Keep trying!

**Comment by chaintip** [comment]
Nice work @mesquka! Your pull request has been merged and the [bounty](http://github.chaintip.org/chaintip/bounties/issues/13) of `0.00229159 BCH`| `~   3.41 USD` has been sent to your wallet.

**Comment by alwaysAn0n** [comment]
YES!  THAT'S IT!  IT'S BITCOIN CASH!  Thanks @mesquka

**Pull request merged**
